In [6]:
# Question-1

import numpy as np

narr=np.array([each for each in range (2,51,3)])
print(narr)



[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [16]:
# Question-2

lst1=list(input().split(' '))
lst2=list(input().split(' '))
arr1=np.array(lst1)
arr2=np.array(lst2)
print(np.concatenate((arr1,arr2)))
print(np.sort(np.concatenate((arr1,arr2))))

1 2 3 5 4
5 1 4 5 5
['1' '2' '3' '5' '4' '5' '1' '4' '5' '5']
['1' '1' '2' '3' '4' '4' '5' '5' '5' '5']


In [17]:
# Question-3
arrr=np.random.rand(5,5)
print(arrr.shape)
print(arrr.size)

(5, 5)
25


In [25]:
#Question-4

art=np.array([1,2,3])
print(art.shape)
art1=art[np.newaxis].shape
art2=np.expand_dims(art,axis=1).shape
print(art1)
print(art2)

(3,)
(1, 3)
(3, 1)


In [31]:
# Question-5
arrr2=np.random.rand(5,5)
print(np.vstack((arrr,arrr2)),"\n")
print(np.hstack((arrr,arrr2)))

[[0.67420428 0.90071048 0.05986794 0.09861676 0.89103289]
 [0.66182427 0.17653068 0.71222297 0.72331191 0.88357488]
 [0.47746781 0.79637653 0.05757795 0.18759139 0.02656688]
 [0.53425121 0.50762846 0.43800635 0.1115203  0.94047517]
 [0.47140548 0.82993763 0.75774658 0.98295831 0.7420798 ]
 [0.93877199 0.48596696 0.42491641 0.55313963 0.12798984]
 [0.58901364 0.18538767 0.51986036 0.47391014 0.36245984]
 [0.6160904  0.23213577 0.92988376 0.83256956 0.84301765]
 [0.28868025 0.26905961 0.89994366 0.37589195 0.30744846]
 [0.74079501 0.51563007 0.5122986  0.95602131 0.57408096]] 

[[0.67420428 0.90071048 0.05986794 0.09861676 0.89103289 0.93877199
  0.48596696 0.42491641 0.55313963 0.12798984]
 [0.66182427 0.17653068 0.71222297 0.72331191 0.88357488 0.58901364
  0.18538767 0.51986036 0.47391014 0.36245984]
 [0.47746781 0.79637653 0.05757795 0.18759139 0.02656688 0.6160904
  0.23213577 0.92988376 0.83256956 0.84301765]
 [0.53425121 0.50762846 0.43800635 0.1115203  0.94047517 0.28868025
  0.2

In [33]:
# Question-6

Array=np.array([1,2,2,5,4,6,8,9,12,1,1,2,5,6,8,9,8,8,5,2,5,12,45,4,5,121,2,1,6,44,4,64,6,6,6,1,31,61])
unique,occur=np.unique(Array,return_counts=True)
print(unique,"\n",occur)

[  1   2   4   5   6   8   9  12  31  44  45  61  64 121] 
 [5 5 3 5 6 4 2 2 1 1 1 1 1 1]
